config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get 'static_pages/home'

  get '/mygossips', to: 'gossips#mygossips'

  devise_for :admins

  resources :gossips

  resources :users

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :created_gossips, foreign_key: "gossiper_id"
  has_many :gossips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :admin

  before_save { self.anonymous_author = anonymous_author.titleize }
  validates :anonymous_author, presence: true, length: { minimum: 2, maximum: 100 }
  validates :content, presence: true, length: { minimum: 2, maximum: 300 }
end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_sign_up_params, if: :devise_controller?

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

=begin
  protected
    def after_sign_in_path_for(resource)
      sign_in_url = new_admin_session_url
      if request.referer == sign_in_url
        redirect_to gossips_path
      else
        stored_location_for(resource) || request.referer || root_path
      end
    end
=end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @gossips = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(gossip_params)
    current_admin.gossips << @gossip
    @gossip.save
    redirect_to @gossip
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to gossip_path
    flash[:success] = "Gossip updated!"
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
    flash[:success] = "Gossip successfully deleted!"
  end

  def mygossips
  end

  private

  def gossip_params
    params.require(:gossip).permit(:anonymous_author, :content, :gossiper_id)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if !admin_signed_in?
      flash.now[:alert] = "No bro, just connect now!"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/edit.html.erb
<h1>Edit Gossip</h1>

<%= form_for @gossip do |f| %>

  <div class="form-group">

    <label>Gossip Author</label>

    <%= f.text_field :anonymous_author, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Gossip Content</label>

    <%= f.text_area :content, class: 'form-control' %>

  </div>

  <div class="form-group">

    <button type="submit">Modify Gossip</button>

  </div>

<% end %>

app/views/gossips/index.html.erb
<h1>All Gossips</h1>

<% if !@gossips.any? %>
  <p>No gossip to display, man. You need to <%= link_to "add your own", new_gossip_path %> NOW!</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Author</th>
        <th>Content</th>
      </tr>
    </thead>

    <tbody>
      <% @gossips.each do |gossip| %>
        <tr>
          <td><%= gossip.anonymous_author%></td>
          <td><%= gossip.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<p><a href="<%= new_gossip_path %>">Try Gossiping URself</a></p>

app/views/gossips/mygossips.html.erb
<h1><%= current_admin.username %>'s Gossips</h1>

<% if !current_admin.gossips.any? %>
  <p>You didn't gossip yet</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Author</th>
        <th>Content</th>
      </tr>
    </thead>

    <tbody>
      <% current_admin.gossips.each do |gossip| %>
        <tr>
          <td><%= gossip.anonymous_author%></td>
          <td><%= gossip.content %></td>
          <td>
            <%= link_to 'View', gossip, :method=>:get%>
            <%= link_to 'Delete', gossip, :method=>:delete%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div><%= link_to "Add New Gossip", new_gossip_path %></div>

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<%= form_for @gossip do |f| %>

  <div class="form-group">

    <label>Gossip Author</label>

    <%= f.text_field :anonymous_author, class: 'form-control' %>

  </div>

  <div class="form-group">

    <label>Gossip Content</label>

    <%= f.text_area :content, class: 'form-control' %>

  </div>

  <div class="form-group">

    <button type="submit">Create Gossip</button>

  </div>

<% end %>

app/views/gossips/show.html.erb
<h1>Your Gossip</h1>

<% if @gossip.created_at == @gossip.updated_at %>
  <p>Created on: <%= @gossip.created_at.strftime("%d/%m/%Y at %H:%M") %></p>
<% else %>
  <p>Updated on: <%= @gossip.updated_at.strftime("%d/%m/%Y at %H:%M") %></p>
<% end %>

<p>Author: <%= @gossip.anonymous_author %></p>

<p>Content:<br / /><%= @gossip.content %></p>

<button><a href="<%= edit_gossip_path %>" class="btn btn-primary">Edit Gossip</a></button>

<button><a href="<%= @gossip %>" class="btn btn-danger" data-confirm="Sure about this?" data-method="DELETE">Delete Gossip</a></button>

<p><a href="<%= gossips_path %>" class="btn btn-default">Back To More Gossips</a></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Powered by <a href="http://simwyck.com/">SimWyck</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div id="logo"><%= link_to "Gossips New Generation", root_path %></div>
    <nav>
      <ul>
        <% if admin_signed_in? %>
          <li><%= link_to "Sign Out", destroy_admin_session_path, method: :delete %></li>
          <li><%= link_to "Edit Account", edit_admin_registration_path %></li>
          <li><%= link_to "Add Your Gossip", new_gossip_path %></li>
          <li><%= link_to "My Gossips", mygossips_path %></li>
          <li><%= link_to "View All Gossips", gossips_path %></li>
        <% else %>
          <li><%= link_to "Sign In", new_admin_session_path %></li>
          <li><%= link_to "Sign Up", new_admin_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossip Revamped</title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <!--<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>-->
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

app/views/static_pages/about.html.erb
<h1>About</h1>

<p>It's all about YOU babe! &#9786;</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

<p>I don't get it. Why would you want to contact me?</p>

app/views/static_pages/home.html.erb
<h1>Gossips Homepage</h1>

<% if admin_signed_in? %>
  <p>Now you can <%= link_to "view all the gossips", gossips_path %>!</p>
<% else %>
  <p>Yo bro', you really need to login/register to this cooooool app!</p>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>

<% @admins = Admin.all %>
<% @admins.each do |user| %>
  <%= admin.username %><br/>
  <%= admin.email %><br/>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>